language: node_js
node_js: 
  - 8.11.0
install: yarn --ignore-engines
script: gatsby clean && gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'testing-gatsbyjs'
  skip_cleanup: true
  acl: public_read
  local_dir: public
